// Generated by CoffeeScript 1.4.0
(function() {
  var API_ADDRESS, API_VERSION, request;

  request = require('superagent');

  API_VERSION = 2;

  API_ADDRESS = 'http://www.hel.fi/palvelukarttaws/rest/v' + API_VERSION;

  module.exports.itemRetrieve = function(model, searchParams, cb) {
    var URL;
    URL = API_ADDRESS + '/' + model + '/';
    if (searchParams != null) {
      if (searchParams.id) {
        URL = URL + searchParams.id + '/';
        searchParams.id = void 0;
      }
      if ((searchParams.accessibility != null) && searchParams.accessibility === true) {
        URL = URL + 'accessibility/';
        searchParams.accessibility = void 0;
      }
    } else {
      searchParams = {};
    }
    request.get(URL).query(searchParams).end(function(err, res) {
      if (err) {
        return cb(err, null);
      } else {
        return cb(null, res.body);
      }
    });
  };

}).call(this);
